export class GET_IMAGE1
{

    /**
     *
     */
    constructor() {
        this.ImagenameList = [

            "Afghani.png",
"Albanian.png",
"American.png",
"Argentinean.png",
"Armenian.png",
"Australian.png",
"Austrian.png",
"Azerbaijani.png",
"Bahamian.png",
"Bangladeshi.png",
"Barbecue.png",
"Belgian.png",
"Brazilian.png",
"British.png",
"Cafe.png",
"Cambodian.png",
"Canadian.png",
"Chilean.png",
"Chinese.png",
"Chinese1.png",
"Colombian.png",
"Contemporary.png",
"Croatian.png",
"Cuban.png",
"Czech.png",
"Egyptian.png",
"Ethiopian.png",
"European.png",
"Family.png",
"French.png",
"Georgian.png",
"German.png",
"Greek.png",
"Grill.png",
"Guatemalan.png",
"Hawaiian.png",
"Hungarian.png",
"Indian.png",
"Indonesian.png",
"Israeli.png",
"Italian.png",
"Jamaican.png",
"Japanese.png",
"Latvian.png",
"Lebanese.png",
"Malaysian.png",
"Mexican.png",
"Middle Eastern.png",
"Mongolian.png",
"Moroccan.png",
"Nepali.png",
"Norwegian.png",
"Pakistani.png",
"Peruvian.png",
"Pizza.png",
"Portuguese.png",
"Pub.png",
"Restaurant.png",
"Russian.png",
"Salvadoran.png",
"Scottish.png",
"SeaFood.png",
"SeaFood4.png",
"Seafood1.jpg",
"Singaporean.png",
"Slovenian.png",
"Southwestern.png",
"Swedish.png",
"Taiw.png",
"Taiwanese.png",
"Thai.png",
"Tibetan.png",
"Tunisian.png",
"Turkish.png",
"Ukrainian.png",
"Vegan Options.png",
"Venezuelan.png",
"Vergetarian Freindly.png",
"Vietnam.png",
"Vietnamese.png",
    ]
        
    }


    public ImagenameList: string[]=[];
    
}