import { GET_IMAGES } from "./../../shared/models/GET_IMAGES";

export class ImagesTest{
    list :GET_IMAGES[]=[];

public GetImage(id:number)
{
    return this.list.filter(
        r => 
            r.Restarantid == id
        
    )
    .sort().slice();

}
aconstructor() {
    this.list = [
        new GET_IMAGES(	29662	,"	Bar	","	 Pub	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	37919	,"	Seafood	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	52778	,"	Italian	","	 Pizza	","	 Cafe	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	37912	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	52910	,"	Asian	","	 Thai	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	8669	,"	Cafe	","	 Sri Lankan	","	 Gluten Free Options	","		","		","		","		","		"),
        new GET_IMAGES(	8999	,"	Australian	","	 Mediterranean	","		","		","		","		","		","		"),
        new GET_IMAGES(	21655	,"	International	","	 Australian	","	 Bar	","	 Pub	","	 Vegetarian Friendly	","		","		","		"),
        new GET_IMAGES(	24887	,"	Asian	","	 Thai	","	 Vegetarian Friendly	","		","		","		","		","		"),
        new GET_IMAGES(	9092	,"	Asian	","	 Korean	","		","		","		","		","		","		"),
        new GET_IMAGES(	8863	,"	Cafe	","	 Asian	","	 Indonesian	","	 Halal	","		","		","		","		"),
        new GET_IMAGES(	25552	,"	Thai	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	12331	,"	Asian	","	 Thai	","		","		","		","		","		","		"),
        new GET_IMAGES(	21383	,"	Cafe	","	 Fast Food	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	41321	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	45514	,"	Bar	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	31388	,"	Fast Food	","	 Australian	","	 Seafood	","		","		","		","		","		"),
        new GET_IMAGES(	45654	,"	Chinese	","	 Asian	","	 Thai	","	 Nepali	","	 Vegan Options	","		","		","		"),
        new GET_IMAGES(	8802	,"	Thai	","	 Vietnamese	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	21717	,"	Asian	","	 Thai	","	 Vietnamese	","	 Street Food	","	 Taiwanese	","		","		","		"),
        new GET_IMAGES(	49238	,"	Japanese	","	 Sushi	","	 Asian	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	16970	,"	Barbecue	","	 Middle Eastern	","	 Pakistani	","	 Indian	","	 Grill	","		","		","		"),
        new GET_IMAGES(	21582	,"	Fast Food	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	37858	,"	American	","	 International	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	36928	,"	Australian	","	 Argentinean	","	 South American	","		","		","		","		","		"),
        new GET_IMAGES(	29467	,"	Bar	","	 Pub	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		"),
        new GET_IMAGES(	12265	,"	Asian	","	 Indonesian	","		","		","		","		","		","		"),
        new GET_IMAGES(	20528	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	30361	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","		","		","		","		","		"),
        new GET_IMAGES(	8541	,"	Cafe	","	 Australian	","	 Fast Food	","		","		","		","		","		"),
        new GET_IMAGES(	55260	,"	Bar	","	 Pub	","	 Australian	","	 Contemporary	","	 Fusion	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	"),
        new GET_IMAGES(	33654	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	3419	,"	Seafood	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	17128	,"	Chinese	","	 Taiwanese	","		","		","		","		","		","		"),
        new GET_IMAGES(	45488	,"	Steakhouse	","	 Bar	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	45712	,"	Australian	","	 Cafe	","		","		","		","		","		","		"),
        new GET_IMAGES(	56716	,"	Bar	","	 Pub	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	57055	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	45375	,"	Cafe	","	 Australian	","	 International	","	 Deli	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		"),
        new GET_IMAGES(	8777	,"	Thai	","	 Australian	","	 Cafe	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	52992	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	31432	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	49406	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	29289	,"	Cafe	","	 Australian	","	 Mediterranean	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	24657	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	3471	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	8647	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	3393	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		"),
        new GET_IMAGES(	12476	,"	Seafood	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	52673	,"	Seafood	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	37976	,"	Bar	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	13301	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	30600	,"	Asian	","	 Bar	","	 Pub	","	 Australian	","	 Vegetarian Friendly	","		","		","		"),
        new GET_IMAGES(	17337	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	52856	,"	Steakhouse	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		","		"),
        new GET_IMAGES(	21406	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	41425	,"	Chinese	","	 Asian	","	 Vietnamese	","	 Malaysian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		"),
        new GET_IMAGES(	57685	,"	Pizza	","	 Fast Food	","	 Australian	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	12323	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	49471	,"	Cafe	","	 Asian	","	 Healthy	","	 Australian	","		","		","		","		"),
        new GET_IMAGES(	33961	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	5143	,"	Australian	","	 Bar	","		","		","		","		","		","		"),
        new GET_IMAGES(	30357	,"	Indian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	45681	,"	Steakhouse	","	 Australian	","	 Gluten Free Options	","		","		","		","		","		"),
        new GET_IMAGES(	21774	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	38232	,"	Pizza	","	 Fast Food	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		"),
        new GET_IMAGES(	3265	,"	Seafood	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	56919	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	49439	,"	Indian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	13228	,"	Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		","		"),
        new GET_IMAGES(	3525	,"	Mediterranean	","	 Lebanese	","		","		","		","		","		","		"),
        new GET_IMAGES(	46481	,"	Lebanese	","	 Mediterranean	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	12197	,"	Seafood	","	 Australian	","	 Fast Food	","		","		","		","		","		"),
        new GET_IMAGES(	21513	,"	Pizza	","	 Fast Food	","	 Turkish	","	 Halal	","		","		","		","		"),
        new GET_IMAGES(	45203	,"	Asian	","	 Malaysian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		"),
        new GET_IMAGES(	21608	,"	Asian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	55243	,"	Bar	","	 Pub	","	 Australian	","	 Vegan Options	","	 Vegetarian Friendly	","		","		","		"),
        new GET_IMAGES(	52504	,"	Bar	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	29384	,"	Asian	","	 Australian	","	 Seafood	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	29438	,"	Asian	","	 Contemporary	","	 Pub	","	 Bar	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","	 Vegan Options	"),
        new GET_IMAGES(	12448	,"	Australian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	29224	,"	French	","	 Vegan Options	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	8491	,"	Bar	","	 Pub	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	33788	,"	Greek	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	48865	,"	Pizza	","	 Fast Food	","	 Italian	","		","		","		","		","		"),
        new GET_IMAGES(	33598	,"	Italian	","	 Pizza	","		","		","		","		","		","		"),
        new GET_IMAGES(	3209	,"	Pizza	","	 Italian	","		","		","		","		","		","		"),
        new GET_IMAGES(	17031	,"	Pizza	","	 Fast Food	","	 Italian	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	8750	,"	Cafe	","	 Australian	","	 American	","	 Vegetarian Friendly	","	 Gluten Free Options	","	 Vegan Options	","		","		"),
        new GET_IMAGES(	35500	,"	Pizza	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	52477	,"	Italian	","	 Pizza	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	24828	,"	Cafe	","	 Australian	","	 Gluten Free Options	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		"),
        new GET_IMAGES(	46421	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	21748	,"	Bar	","	 Australian	","	 Vegetarian Friendly	","		","		","		","		","		"),
        new GET_IMAGES(	46458	,"	Italian	","	 Asian	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	45321	,"	Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		","		"),
        new GET_IMAGES(	38212	,"	Australian	","	 Gluten Free Options	","		","		","		","		","		","		"),
        new GET_IMAGES(	41355	,"	Indian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	24758	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		"),
        new GET_IMAGES(	29562	,"	Cafe	","	 Australian	","	 Vegan Options	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	49322	,"	Italian	","	 Pizza	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	3038	,"	Irish	","	 Bar	","	 Pub	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		"),
        new GET_IMAGES(	31382	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	49278	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	17213	,"	Italian	","	 Pizza	","		","		","		","		","		","		"),
        new GET_IMAGES(	31357	,"	Asian	","	 Australian	","	 Cafe	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		"),
        new GET_IMAGES(	12513	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	31396	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	58478	,"	Japanese	","	 Sushi	","	 Asian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		"),
        new GET_IMAGES(	52961	,"	American	","	 Bar	","	 Pub	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		"),
        new GET_IMAGES(	16857	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	52727	,"	Cafe	","	 Australian	","	 Healthy	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		"),
        new GET_IMAGES(	3337	,"	Indian	","	 Thai	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	33506	,"	Australian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		","		"),
        new GET_IMAGES(	8522	,"	Australian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	29501	,"	German	","	 Austrian	","	 European	","		","		","		","		","		"),
        new GET_IMAGES(	37663	,"	Indian	","	 Thai	","	 Singaporean	","	 Sri Lankan	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		"),
        new GET_IMAGES(	41426	,"	Chinese	","	 Asian	","		","		","		","		","		","		"),
        new GET_IMAGES(	52556	,"	Austrian	","	 European	","		","		","		","		","		","		"),
        new GET_IMAGES(	46425	,"	Bar	","	 Pub	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	17157	,"	Bar	","	 Pub	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	35314	,"	Cafe	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	37783	,"	Chinese	","	 Asian	","		","		","		","		","		","		"),
        new GET_IMAGES(	38098	,"	American	","	 Steakhouse	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		"),
        new GET_IMAGES(	30416	,"	Steakhouse	","	 Bar	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	3152	,"	Australian	","	 Vegetarian Friendly	","		","		","		","		","		","		"),
        new GET_IMAGES(	57792	,"	Mexican	","	 Central American	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	41973	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	41885	,"	Bar	","	 Pub	","	 Australian	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	31531	,"	Fast Food	","	 American	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	49257	,"	Fast Food	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	30642	,"	Pizza	","	 Barbecue	","		","		","		","		","		","		"),
        new GET_IMAGES(	21433	,"	Australian	","	 Italian	","	 Pizza	","	 Seafood	","	 Vegetarian Friendly	","		","		","		"),
        new GET_IMAGES(	45605	,"	Italian	","	 Pizza	","	 Australian	","	 Vegan Options	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		"),
        new GET_IMAGES(	24883	,"	Indian	","	 Asian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","	 Halal	","		","		"),
        new GET_IMAGES(	35680	,"	Indian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	21549	,"	Fast Food	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	45738	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","		","		","		","		","		"),
        new GET_IMAGES(	29355	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	21435	,"	Chinese	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	8975	,"	International	","	 Contemporary	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	9058	,"	Mediterranean	","	 Greek	","		","		","		","		","		","		"),
        new GET_IMAGES(	38130	,"	Cafe	","	 Australian	","	 Healthy	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		"),
        new GET_IMAGES(	8694	,"	Nepali	","	 Indian	","	 Asian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		"),
        new GET_IMAGES(	16773	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	35584	,"	Fast Food	","	 American	","		","		","		","		","		","		"),
        new GET_IMAGES(	8723	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	35368	,"	Chinese	","	 Asian	","		","		","		","		","		","		"),
        new GET_IMAGES(	33563	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	13276	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	20554	,"	Australian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	56921	,"	Asian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	24854	,"	Australian	","	 Cafe	","	 Vegetarian Friendly	","	 Gluten Free Options	","	 Vegan Options	","		","		","		"),
        new GET_IMAGES(	37881	,"	Chinese	","	 Asian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	8598	,"	Fusion	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	17186	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	20582	,"	Italian	","	 Mexican	","	 Indian	","	 Asian	","		","		","		","		"),
        new GET_IMAGES(	36887	,"	Australian	","	 Bar	","	 Cafe	","	 Pub	","		","		","		","		"),
        new GET_IMAGES(	56757	,"	Barbecue	","	 Asian	","	 Korean	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		"),
        new GET_IMAGES(	16938	,"	Bar	","	 Pub	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	52585	,"	Bar	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	33880	,"	Chinese	","	 Seafood	","	 Asian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	17331	,"	Australian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	9025	,"	Australian	","	 Cafe	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		"),
        new GET_IMAGES(	24778	,"	Cafe	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	38067	,"	Cafe	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	21813	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	37715	,"	Greek	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	38007	,"	Cafe	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	33681	,"	Fast Food	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	3291	,"	Fast Food	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	35407	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	21632	,"	American	","	 Fast Food	","		","		","		","		","		","		"),
        new GET_IMAGES(	35401	,"	Fast Food	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	52643	,"	Asian	","	 Chinese	","	 Vietnamese	","		","		","		","		","		"),
        new GET_IMAGES(	8895	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	52752	,"	Cafe	","	 Asian	","	 Thai	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		"),
        new GET_IMAGES(	24803	,"	Indian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		","		"),
        new GET_IMAGES(	33418	,"	Chinese	","	 Asian	","	 Pizza	","		","		","		","		","		"),
        new GET_IMAGES(	30619	,"	Indian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	12191	,"	Italian	","	 Pizza	","	 Fast Food	","		","		","		","		","		"),
        new GET_IMAGES(	8832	,"	Grill	","	 Australian	","	 Steakhouse	","	 Seafood	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	48832	,"	Bar	","	 Pub	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	33907	,"	Moroccan	","	 Mediterranean	","	 Spanish	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		"),
        new GET_IMAGES(	30440	,"	Cafe	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	12480	,"	Japanese	","	 Sushi	","	 Asian	","	 Fast Food	","		","		","		","		"),
        new GET_IMAGES(	52699	,"	Asian	","	 Vietnamese	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		"),
        new GET_IMAGES(	31497	,"	European	","	 Portuguese	","		","		","		","		","		","		"),
        new GET_IMAGES(	17271	,"	Portuguese	","	 Fast Food	","	 European	","		","		","		","		","		"),
        new GET_IMAGES(	52639	,"	European	","	 Portuguese	","		","		","		","		","		","		"),
        new GET_IMAGES(	21465	,"	Australian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	3180	,"	Fast Food	","	 Australian	","	 Seafood	","	 Asian	","		","		","		","		"),
        new GET_IMAGES(	33602	,"	Pizza	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	46413	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	45182	,"	Indian	","	 Asian	","	 Thai	","	 Malaysian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		"),
        new GET_IMAGES(	12259	,"	Asian	","	 Thai	","	 Vietnamese	","		","		","		","		","		"),
        new GET_IMAGES(	57761	,"	Chinese	","	 Asian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	20471	,"	Steakhouse	","	 Bar	","	 Pub	","	 Australian	","		","		","		","		"),
        new GET_IMAGES(	29628	,"	Pizza	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	45546	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		"),
        new GET_IMAGES(	49446	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	30645	,"	Turkish	","	 Fast Food	","	 Middle Eastern	","	 Halal	","	 Vegetarian Friendly	","		","		","		"),
        new GET_IMAGES(	55225	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	30391	,"	Chinese	","	 Asian	","	 Malaysian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		"),
        new GET_IMAGES(	33471	,"	Japanese	","	 Sushi	","	 Asian	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	12165	,"	Steakhouse	","	 Bar	","	 Barbecue	","	 Australian	","		","		","		","		"),
        new GET_IMAGES(	48917	,"	Seafood	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	48838	,"	Thai	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	30719	,"	Bar	","	 Pub	","	 Australian	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	30692	,"	Bar	","	 Pub	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	41392	,"	Asian	","	 Malaysian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		"),
        new GET_IMAGES(	57848	,"	Bar	","	 Pub	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	24705	,"	Australian	","	 International	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	52534	,"	Bar	","	 Asian	","	 Pub	","	 Australian	","		","		","		","		"),
        new GET_IMAGES(	41296	,"	Pizza	","	 Italian	","		","		","		","		","		","		"),
        new GET_IMAGES(	8949	,"	Pizza	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	35607	,"	Fast Food	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	52722	,"	Pizza	","	 Fast Food	","		","		","		","		","		","		"),
        new GET_IMAGES(	33856	,"	Seafood	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","	 Vegan Options	","		","		","		"),
        new GET_IMAGES(	3367	,"	Australian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	21685	,"	Asian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	29735	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","		","		","		","		","		"),
        new GET_IMAGES(	33707	,"	Mexican	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		","		"),
        new GET_IMAGES(	48807	,"	Cafe	","	 Australian	","	 Fusion	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	37636	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	33630	,"	Seafood	","	 Australian	","	 Gluten Free Options	","		","		","		","		","		"),
        new GET_IMAGES(	29192	,"	Japanese	","	 Cafe	","	 Sushi	","	 Asian	","	 Vegetarian Friendly	","		","		","		"),
        new GET_IMAGES(	29416	,"	Bar	","	 Pub	","	 Australian	","	 European	","		","		","		","		"),
        new GET_IMAGES(	17301	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	17091	,"	Cafe	","	 Australian	","	 Healthy	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		"),
        new GET_IMAGES(	31424	,"	Chinese	","	 Asian	","		","		","		","		","		","		"),
        new GET_IMAGES(	21536	,"	Fast Food	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	35438	,"	Fast Food	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	57006	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	56867	,"	Cafe	","	 Asian	","	 Malaysian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	52456	,"	Chinese	","	 Asian	","		","		","		","		","		","		"),
        new GET_IMAGES(	52829	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	17241	,"	International	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	57820	,"	Bar	","	 Pub	","	 Australian	","	 Fusion	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	45354	,"	Asian	","	 Vietnamese	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	36862	,"	Bar	","	 Pub	","	 Australian	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	29259	,"	Indian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	31526	,"	Asian	","	 Vietnamese	","		","		","		","		","		","		"),
        new GET_IMAGES(	45232	,"	Mexican	","	 Fast Food	","		","		","		","		","		","		"),
        new GET_IMAGES(	26076	,"	Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	21604	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	56813	,"	Italian	","	 Pizza	","	 Cafe	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	21681	,"	Australian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	49299	,"	Indonesian	","	 Asian	","	 Halal	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	25550	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	38186	,"	Seafood	","	 Asian	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	16915	,"	Irish	","	 Bar	","	 Pub	","		","		","		","		","		"),
        new GET_IMAGES(	49138	,"	Irish	","	 Bar	","	 European	","	 Pub	","	 Vegetarian Friendly	","		","		","		"),
        new GET_IMAGES(	29622	,"	Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		","		","		"),
        new GET_IMAGES(	21294	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	57731	,"	Brew Pub	","	 Bar	","	 Pub	","	 Australian	","	 Wine Bar	","	 Vegetarian Friendly	","		","		"),
        new GET_IMAGES(	46536	,"	Australian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	3104	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	45737	,"	Australian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		","		"),
        new GET_IMAGES(	17274	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	8624	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	24684	,"	Sri Lankan	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	56946	,"	Asian	","	 Nepali	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	3316	,"	Asian	","	 Chinese	","	 Vegetarian Friendly	","		","		","		","		","		"),
        new GET_IMAGES(	35554	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	9029	,"	Cafe	","	 Indonesian	","	 Fast Food	","	 Asian	","	 Healthy	","	 Vegetarian Friendly	","		","		"),
        new GET_IMAGES(	17099	,"	Australian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	56713	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	33416	,"	Cafe	","	 Greek	","		","		","		","		","		","		"),
        new GET_IMAGES(	56978	,"	Australian	","	 Contemporary	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	12293	,"	Indian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	57764	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	21265	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	33737	,"	Asian	","	 Thai	","		","		","		","		","		","		"),
        new GET_IMAGES(	52528	,"	Asian	","	 Thai	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	30521	,"	Bar	","	 Australian	","	 Asian	","	 Pub	","		","		","		","		"),
        new GET_IMAGES(	30462	,"	Pizza	","	 Cafe	","	 Pub	","	 Australian	","	 Gastropub	","	 Vegetarian Friendly	","		","		"),
        new GET_IMAGES(	3242	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	45435	,"	Bar	","	 Pub	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	29326	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","		","		","		","		","		"),
        new GET_IMAGES(	52986	,"	Fast Food	","	 Australian	","	 Irish	","	 Seafood	","	 British	","	 Vegetarian Friendly	","		","		"),
        new GET_IMAGES(	52933	,"	Fast Food	","	 Australian	","	 Vegetarian Friendly	","		","		","		","		","		"),
        new GET_IMAGES(	35362	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	13328	,"	Healthy	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	8567	,"	Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","	 Vegan Options	","		","		","		"),
        new GET_IMAGES(	49349	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	45578	,"	Bar	","	 Pub	","	 Australian	","	 Fusion	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		"),
        new GET_IMAGES(	24735	,"	Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	30549	,"	Bar	","	 Australian	","	 Grill	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	49399	,"	International	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	29469	,"	Australian	","	 Cafe	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	37748	,"	Australian	","	 Vegetarian Friendly	","	 Vegan Options	","		","		","		","		","		"),
        new GET_IMAGES(	3064	,"	Seafood	","	 Asian	","	 Australian	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	35467	,"	Pub	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	16942	,"	Thai	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	3175	,"	Bar	","	 Pub	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	33936	,"	Chinese	","	 Asian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	20606	,"	Steakhouse	","	 Grill	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	56898	,"	Steakhouse	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	8921	,"	Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	8953	,"	Cafe	","	 Australian	","		","		","		","		","		","		"),
        new GET_IMAGES(	33538	,"	Polynesian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	52437	,"	Bar	","	 Pub	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		"),
        new GET_IMAGES(	5131	,"	Pizza	","	 Cafe	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	25607	,"	Greek	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	49208	,"	Bar	","	 Australian	","	 Pub	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		"),
        new GET_IMAGES(	17367	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	3612	,"	American	","	 Seafood	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		"),
        new GET_IMAGES(	21492	,"	Cafe	","	 Asian	","	 Healthy	","	 Australian	","	 Taiwanese	","		","		","		"),
        new GET_IMAGES(	12336	,"	Vietnamese	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	38036	,"	Seafood	","	 Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		"),
        new GET_IMAGES(	17000	,"	Australian	","	 Cafe	","	 Fast Food	","	 British	","		","		","		","		"),
        new GET_IMAGES(	52613	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	52890	,"	Bar	","	 Pub	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	49167	,"	Cafe	","	 Australian	","	 Vegan Options	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	53022	,"	Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","		","		","		","		","		"),
        new GET_IMAGES(	56786	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	12301	,"	Australian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	16917	,"	Fast Food	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	16800	,"	Cafe	","	 Australian	","	 Gluten Free Options	","		","		","		","		","		"),
        new GET_IMAGES(	3125	,"	Asian	","	 Vietnamese	","	 Soups	","	 Vegetarian Friendly	","	 Gluten Free Options	","	 Vegan Options	","		","		"),
        new GET_IMAGES(	38701	,"	Cafe	","	 Fast Food	","	 Australian	","		","		","		","		","		"),
        new GET_IMAGES(	12168	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	46351	,"	Seafood	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	45256	,"	Australian	","	 Vegetarian Friendly	","	 Gluten Free Options	","	 Vegan Options	","		","		","		","		"),
        new GET_IMAGES(	49185	,"	Bar	","	 Pub	","	 Australian	","	 Vegetarian Friendly	","	 Vegan Options	","	 Gluten Free Options	","		","		"),
        new GET_IMAGES(	3614	,"	Restaurant	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	17327	,"	Cafe	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	57711	,"	Australian	","	 Nepali	","		","		","		","		","		","		"),
        new GET_IMAGES(	33768	,"	Mediterranean	","	 Greek	","	 Gluten Free Options	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	49443	,"	Asian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	13148	,"	Mexican	","	 Fast Food	","		","		","		","		","		","		"),
        new GET_IMAGES(	8492	,"	Australian	","	 Gluten Free Options	","		","		","		","		","		","		"),
        new GET_IMAGES(	12226	,"	Chinese	","	 Fast Food	","	 Asian	","	 Vegetarian Friendly	","		","		","		","		"),
        new GET_IMAGES(	16947	,"	Asian	","		","		","		","		","		","		","		"),
        new GET_IMAGES(	3552	,"	Asian	","	 Korean	","	 Barbecue	","	 Vegetarian Friendly	","		","		","		","		")
      ];
      
  
}

}